books/urls.py
from django.urls import path,re_path
from . import views
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import logout
# from django.views.generic import list_detail

app_name = 'books'

urlpatterns=[
	re_path(r'^$', views.home, name='home'),
	re_path(r'^register/', views.register, name='register'),
	re_path(r'^login$', views.checkLogin, name='check-login'),
    re_path(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
	re_path(r'^reg$', views.checkRegister, name='check-register'),
	path('author/<int:pk>', views.AuthorView.as_view(), name='author-detail'),
	path('authors/', views.AuthorList.as_view(), name='author-list'),
	path('book/<int:pk>/', views.BookView.as_view(), name='book-detail'),
	path('books/', views.BookList.as_view(), name='book-list'),
	path('categories/', views.CategoryList.as_view(), name='category-list'),
    path('categories/<int:pk>', views.CategoryView.as_view(), name='category-detail'),
	path('service1/<int:id>', views.service1, name="service1"),
	re_path(r'^book/([0-9]+)/rate$', views.service2, name="service2"),
    path('service3/', views.service3, name="service3"),
	re_path(r'^book/([0-9]+)/edit$', views.service4, name="service4"),
	path('service5/<str:status>', views.service5, name="service5"),
	path('search/', views.search, name="search"),
	path('ssearch/<str:keyword>', views.searchService, name="search-service"),
	path('Status/<int:id>', views.Status, name="Status"),
]

stickToBox/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# from books.views import author, book

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^',include('books.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='images/users/')

    def __str__(self):
        return self.user.get_full_name()


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField()
    date_of_death = models.DateField(null=True, blank=True)
    bio = models.TextField()
    picture = models.ImageField(upload_to='images/authors/') 

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    name = models.CharField(max_length=70)
    image = models.ImageField(upload_to='images/categories/') # will add upload to attribute later!
    profile = models.ManyToManyField(Profile, through='ProfileCategory')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=70)
    summary = models.TextField()
    date_of_publish = models.DateField()
    image = models.ImageField(upload_to='images/books/') 
    author = models.ManyToManyField(Author)
    category = models.ManyToManyField(Category)
    profile = models.ManyToManyField(Profile, through='ProfileBook')

    def __str__(self):
        return self.title
    
class ProfileBook(models.Model):
    STATUS = (
        ('wishlist', 'Add To Wishlist'),
        ('read', 'Read'),
        ('reading', 'Currently Reading'),
    )

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS)
    rate =  models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])
    comment = models.TextField()

class ProfileCategory(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    fav = models.NullBooleanField()

books/forms.py
from django import forms

class RegistrationForm(forms.Form):
    username = forms.CharField(label="User Name", widget=forms.TextInput(attrs={'placeholder': 'Type your Username','class':'form-control','id':'email-signup'}), max_length=25)
    email = forms.EmailField(label="Email",widget=forms.TextInput(attrs={'placeholder': 'email@example.com','class':'form-control','id':'email-signup'}),max_length=50)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'placeholder': 'Type your Password','class':'form-control','id':'password-signup'}),min_length=6)
    repass = forms.CharField(label="Retype Password",widget=forms.PasswordInput(attrs={'placeholder': 'Retype Password','class':'form-control','id':'password-confirm-signup'}),min_length=6)
    img = forms.ImageField(label="Profile Picture")

class LoginForm(forms.Form):
    username = forms.CharField(label="User Name", widget=forms.TextInput(attrs={'placeholder': 'Type your Username','class':'form-control','id':'email-login'}), max_length=25)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'placeholder': 'Type your Password','class':'form-control','id':'password'}),min_length=6)

books/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login as authlogin, logout as authlogout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.views import generic
from django.db.models import Q
from .models import *
from django.views.generic import ListView, DetailView
from .forms import RegistrationForm, LoginForm
from django.template import Context, Template
import math

# Create your views here.

class AuthorView(DetailView):
    model = Author

class AuthorList(ListView):
    model = Author

class BookView(DetailView):
    model = Book

class BookList(ListView):
    model = Book

class CategoryList(ListView):
    model = Category

class CategoryView(DetailView):
    model = Category


def checkLogin (request):
    form = LoginForm(request.POST)
    if request.method == 'POST' :
        uname = request.POST.get('username')
        passwd = request.POST.get('password')
        user = authenticate(username=uname,password=passwd)
        if user is not None:
            authlogin(request,user)
            return render(request,"books/index.html")
        else :
            regForm = RegistrationForm()
            return render(request,'books/index.html',{'rform':regForm, 'lform':form, 'error':'Either Usernme or Password is not correct'})
    else:
        return redirect('books:register')

def checkRegister(request):
    form = RegistrationForm(request.POST, request.FILES)
    logForm = LoginForm()
    username = request.POST.get('username')
    existUsr = User.objects.filter(username=username).exists()
    if not existUsr:
        if form.is_valid():
            profile = Profile()
            usr = User(request.POST, request.FILES['img'])
            prof = Profile(request.FILES['img'])
            email = request.POST.get('email')
            password = request.POST.get('password')
            repass = request.POST.get('repass')
            if password != repass:
                return render(request,'books/index.html',{'rform':form, 'lform':logForm, 'pass_err':'Password does not match'})
            else :
                newUser=User.objects.create_user(username=username,email=email,password=password)
                profile.user=newUser
                profile.profile_picture=form.cleaned_data['img']
                profile.save()
                return render(request,"books/home.html")
        else:
            return render(request,'books/index.html',{'rform':form, 'lform':logForm})
    else : 
        return render(request,'books/index.html',{'rform':form, 'lform':logForm, 'user_errors':'this user name already exists'})
        # return redirect('books:register')

def register(request):
    regForm = RegistrationForm()
    logForm = LoginForm()
    category_list = Category.objects.all()
    book_list = Book.objects.all()
    return render(request, 'books/index.html',
        {'rform': RegistrationForm, 'lform': LoginForm,
        'category_list': category_list, 'book_list': book_list})

# @login_required(login_url='books:register')
@login_required(login_url='books:register')
def home (request):
    # if User.is_authenticated:
        # user_image = User.Profile_set.filter(username='a7mad').profile_picture
    category_list = Category.objects.all()
    book_list = Book.objects.all()
    return render(request, 'books/home.html',
        {'category_list': category_list, 'book_list': book_list})

# def logout(request):
#     authlogout(request)
#     return redirect('books:register')


def service1(request, id):
    book = get_object_or_404(Book, id=id)
    rateSum = 0
    counter = 0

    for item in book.profilebook_set.all():
        rateSum += item.rate
        counter += 1

    rateAverage = math.ceil(rateSum / counter)    
    return JsonResponse(rateAverage, safe=False)


def service2(request, id):
    if request.user.is_authenticated :
        myBook=get_object_or_404(Book,id = id)
        rate = request.GET.get('rate')
        profilebook = ProfileBook.objects.filter(profile=request.user.profile, book=myBook)
        if bool(profilebook):
            profilebook.update(rate=rate)
        else:
            ProfileBook.objects.create(profile=request.user.profile, book=myBook, rate=rate)
        return JsonResponse("success",safe=False)
    else:
        return redirect('books:register')

def service3(request):
    status = ProfileBook.STATUS
    return JsonResponse(status,safe=False)

@login_required(redirect_field_name='returnURL', login_url='books:register')
def Status(request, id):
    myBook=get_object_or_404(Book, id = id)
    profilebook = ProfileBook.objects.filter(profile=request.user.profile, book=myBook)
    curstatus = profilebook[0].status
    return JsonResponse(curstatus,safe=False)

# @login_required(redirect_field_name='returnURL', login_url='books:register')
def service4(request, Id):
    if request.user.is_authenticated :
        myBook=get_object_or_404(Book,id = Id)
        stat = request.GET.get('status')
        profilebook = ProfileBook.objects.filter(profile=request.user.profile, book=myBook)
        if bool(profilebook):
            profilebook.update(status=stat)
        else:
            ProfileBook.objects.create(profile=request.user.profile, book=myBook, status=stat)
        return JsonResponse("success",safe=False)
    else:
        return redirect('books:register')


def search(request):
    return render(request, 'books/search.html')

def searchService(request, keyword):
    book_results = Book.objects.filter(title__iexact=keyword.strip()).values()
    author_results = Author.objects.filter(first_name__iexact=keyword.strip()).values()
    category_results = Category.objects.filter(name__iexact=keyword.strip()).values()

    return JsonResponse({'results': [list(author_results), list(book_results), list(category_results)]})

def service5(request, status):
    d = eval(status)
    myProfile = get_object_or_404(Profile, id=request.user.profile.id)
    myCategory = get_object_or_404(Category, id=int(d['c_id']))

    if ProfileCategory.objects.filter(profile=myProfile, category=myCategory):
        ProfileCategory.objects.filter(profile=myProfile, category=myCategory).update(fav=(1 if d['fav'] == 'true' else 0))
    else:
        ProfileCategory.objects.create(profile=myProfile, category=myCategory, fav=(1 if d['fav'] == 'true' else 0))
    
    return JsonResponse(status, safe=False)

books/templates/books/base.html
<!doctype html {% load static %}>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block title%}
    {% endblock %}
  </title>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/rating.css" %}">
   <!-- bootstrap default styling file-->
  <!-- <link rel="stylesheet" href="{% static "css/myorders.css" %}"> -->
</head>
<body>
  <!-- Navigation Bar-->
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'books:home' %}">StickToBox</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'books:author-list' %}">Authors<span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'books:category-list' %}">Categories</a>
        <a class="nav-item nav-link" href="{% url 'books:book-list' %}">Books</a>
        <a class="nav-item nav-link" href="{% url 'books:search' %}">Search</a>
      </div>
      {% if user.is_authenticated %}
      <!-- if logged in -->
      <div class="nav-item nav-link">
        <a href="{% url 'books:home' %}"> <!-- edit profile page -->
          <img class="avatar img-responsive mr-1" style="height: 30px; width: 30px; object-fit: cover;" src="{{ request.user.profile.profile_picture.url }}">
          <span class="header-username">{{ request.user.username }}</span>
        </a>
        <!-- <img class="d-inline-block " src="#" alt=""> -->
        | 
        <a href="{% url 'books:logout' %}">log out</a>
      </div>
      <!-- if logged in -->
      {% else %}
      <!-- if not logged in -->
      <form class="form-inline" action="{% url 'books:check-login' %}" method="POST" > <!-- make it not flex ??-->
        {% csrf_token %}
        {% for field in lform %}
        <div class="form-group m-1">
          {{ field }}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary m-1">Sign In</button>
      </form>
      <!-- if not logged in -->
      {% endif %}
    </div>
  </nav>
  <!-- Navigation Bar-->
  <div class="container p-5">
  <!-- body content block-->
  {% block content %}
  {% endblock %}
  <!-- body content block-->
  </div>
</body>
  <!-- <script src="{% static "js/login.js" %}"></script> -->
</html>

books/templates/books/book_detail.html
{% extends 'books/base.html' %}
{% load static %}
{% block content %}
<style type="text/css" media="screen">
  .imag {
    height: 130px;
  }

  .rating {
    unicode-bidi: bidi-override;
    direction: rtl;
  }

  .rating>span {
    display: inline-block;
    position: relative;
    width: 1.1em;
  }

  .rating1>span:hover:before,
  .rating1>span:hover~span:before {
    content: "\2605";
    position: absolute;
  }
</style>
<!-- body block-->
<div class="row">
  <div class="col m-1">
    <div class="row">
      <div class="mr-3">
        <!-- Image -->
        <div class="row">
          <div class="border">
            <img class="m-1" src="{{ book.image.url }}" alt="StickToBox" width="200px" height="250px" style="object-fit: cover;">
          </div>
        </div>
        <div class="row my-3">
            <div class="col">
                    <div>
                            <select id="select" name="status">
                                <option id="default"></option>
                            </select>
                        </div>
                        <div id="rate" class="rating rating1">
                        <input type="radio" id="Star5" name="rating1" value="5" />
                        <label for="Star5" title="Rocks!">5 Stars</label>
                        <input type="radio" id="Star4" name="rating1" value="4" />
                        <label for="Star4" title="Pretty good">4 Stars</label>
                        <input type="radio" id="Star3" name="rating1" value="3" />
                        <label for="Star3" title="Meh">3 Stars</label>
                        <input type="radio" id="Star2" name="rating1" value="2" />
                        <label for="Star2" title="Kinda bad">2 Stars</label>
                        <input type="radio" id="Star1" name="rating1" value="1" />
                        <label for="Star1" title="Sucks big time">1 Star</label>
                      </div>
            </div>
        </div>
        <!-- Image -->
      </div>
      <div class="col m-2">
        <h1>Book Information</h1>
        <!-- Book information -->
        <div class="row">
          <div class="col bg-light mb-2 mx-2">
            <h3 class="m-3">Book Information</h3>
            <h5 class="mx-3">Name: <span class="">{{ book.title }}</span></h5>
            <h5 class="mx-3">By: <span class="">{{book.author.all.0.full_name}}</span></h5>
            <h5 class="mx-3 mb-3">Rating: </h5>
            <div class="mx-3">
              <div id="overAllRate" class="rating">
                <input type="radio" id="star5" name="rating" value="5" disabled/>
                <label for="star5" title="Rocks!">5 stars</label>
                <input type="radio" id="star4" name="rating" value="4" disabled/>
                <label for="star4" title="Pretty good">4 stars</label>
                <input type="radio" id="star3" name="rating" value="3" disabled/>
                <label for="star3" title="Meh">3 stars</label>
                <input type="radio" id="star2" name="rating" value="2" disabled/>
                <label for="star2" title="Kinda bad">2 stars</label>
                <input type="radio" id="star1" name="rating" value="1" disabled/>
                <label for="star1" title="Sucks big time">1 star</label>
              </div>
            </div>
          </div>
          <div class="col bg-light mb-2 mx-2">
            <h3 class="m-3">Description</h3>
            <p class="text-justify mx-3">{{ book.summary }}</p>
          </div>
        </div>
        <!-- Book information -->
        <div class="row">
          <div class="col-10 p-3">
            <div class="row"><h2 class="col">Reviews</h2></div>
            <div class="row">
              <div class="col border">
                {% for commentObject in book.profilebook_set.all %}
                <div class="row">
                  <div class="col-md-3">
                    <img class="m-3" style="object-fit: cover;" src="{% static "img/book.png" %}" width="80px" height="80px" alt="">
                  </div>
                  <div class="col m-3">
                    <p>{{ commentObject.comment }}</p>
                  </div>
                </div>
                {% endfor %}
<!--                 {% if user.is_authenticated %}
                <div class="row m-3">
                  <div class="col">
                    <input type="text" class="form-control" placeholder="comment">
                  </div>
                </div>
                {% endif %} -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- body block-->
<script>
  function rateValue() {
    var inputs = document.getElementsByTagName('input');
    for (var i = 0; i < inputs.length; i++) {
        if (inputs[i].checked) {
            return parseInt(inputs[i].value);
        }
      }
  }

  function printRate(x) {
      if (x >= 1 && x <= 5) {
          document.getElementById('star'+x).checked = true;
      } 
  }

  function clearRate() {
      var inputs = document.getElementsByName('rating1');
      for (var i=0; i<inputs.length; i++) {
          inputs[i].checked = false;
      }
  }

  document.body.onload = function(e) {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function () {
        if (this.readyState == 4 && this.status == 200) {
            var response = this.responseText;
            response = JSON.parse(response);
            printRate(response);
        }
    };
    xhttp.open("GET", "{% url 'books:service1' book.id %}", true);
    xhttp.send();
}
    var stats = []
	  select=document.getElementById('select')
      function ajaxSuccess ()
		{
		  var response =JSON.parse(this.responseText)
		  // console.log(response)
		  for (var i = 0; i < response.length; i++) {
		  	console.log(response[i][1])
		  	option = document.createElement('option')
			option.innerHTML=response[i][1]
			option.value=response[i][0]
			option.id=response[i][0]
			select.appendChild(option)
		  };
		}
		
		function curStatus()
		{
		  var response =JSON.parse(this.responseText)
		  Default = document.getElementById('default')
		  option = document.getElementById(response).textContent
		  Default.innerHTML=''
		  console.log(response)
		  Default.innerHTML = option
		  // select.value=response
		  
		}

		document.addEventListener("DOMContentLoaded", function () {
		    var oReq = new XMLHttpRequest();
		    oReq.onload = ajaxSuccess;
		    oReq.open("GET", "{% url 'books:service3' %}", true);		    
		    oReq.send();

		})
		
		document.addEventListener("DOMContentLoaded", function () {    
		    var req = new XMLHttpRequest();
		    req.onload = curStatus;
		    req.open("GET", "{% url 'books:Status' book.id %}");	
		    req.send();
		})
		function ajaxSuccesss(){
			console.log("hello")
			res = (this.responseText)
			// console.log(res)
		}
		select.addEventListener('change', function(e) {
			var Req = new XMLHttpRequest();
		    Req.onload = ajaxSuccesss;
		    var selVal = select.value;
		    console.log(selVal)
		    Req.open("get", window.location.href+`edit?status=${selVal}`,true);
		    Req.send();
		})

		rating=document.getElementById('rate')
		rate.addEventListener('click', function(e) {
		console.log(e.target.value)
		if (e.target.value)
			{
				var starReq = new XMLHttpRequest();
			    starReq.onload = ajaxSuccesss;
			    var Rate = e.target.value;
			    console.log(Rate)
			    starReq.open("get", window.location.href+`rate?rate=${Rate}`,true);
			    starReq.send();
		    }
		})
</script>
{% endblock %}

books/templates/books/category_detail.html
{% extends 'books/base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
<!-- body block-->
<h1>Category {{ category.name }}</h1>
<div class="row mt-4">
  <div class="table-responsive m-2">
    <table class="table table-hover table-striped">
      <thead align="row">
        <tr class="table-info">
          <th>Book Number</th>
          <th>Book Picture</th>
          <th>Book Name</th>
        </tr>
      </thead>
      <tbody>
        {% for item in category.book_set.all %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td><img style="object-fit: cover;" src="{{ item.image.url }}" alt="" height="90" width="70"></td>
          <td><a href="{% url 'books:book-detail' item.id %}">{{ item.title }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- body block-->
<script src=""></script>
{% endblock %}

books/templates/books/index.html
{% extends 'books/base.html' %}
{% block content %}
<div class="row">
	<!-- body block-->
  <div class="col m-1">
    <div class="row">
      <!-- Image -->
      <img class="bg-dark m-1" src="https://static01.nyt.com/images/2016/05/25/books/review/25bestseller-logo/25bestseller-logo-videoLarge.jpg" alt="StickToBox" width="200px" height="200px" style="object-fit: cover;">
      <!-- Image -->
      <div class="col card border-info m-3">
        <div class="card-body text-info">
          <h5 class="card-title">Of Mice And Men</h5>
          <p class="card-text text-justify">
            <p>Author: John Steinbeck</p>
            <p>Year: 1937</p>
            <p class="text-justify">"Maybe everybody in the whole damn world is scared of each other."</p>
          </p>
        </div>
      </div>
      <div class="col card border-info m-3">
        <div class="card-body text-info">
          <h5 class="card-title">Of Mice And Men</h5>
          <p class="card-text text-justify">
            <p>Author: Ralph Ellison</p>
            <p>Year: 1952</p>
            <p class="text-justify">"Life is to be lived, not controlled; and humanity is won by continuing to play in face of certain defeat."</p>
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <!-- Categories block -->
      <div class="col-md m-2 bg-light">
        <h2 class="text-center">Categories</h2>
        <ul>
          {% for item in category_list %}
          <li class=""><a href="{% url 'books:category-detail' item.id %}">{{ item.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <!-- Categories block -->
      <!-- Books block -->
      <div class="col-md m-2 bg-light">
        <h2 class="text-center">Books</h2>
        <ul>
          {% for item in book_list %} <!-- ???????????? -->
          <li><a href="{% url 'books:book-detail' item.id %}">{{ item.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <!-- Books block -->
    </div>
  </div>
	<!-- body block-->
	{% if not user.is_authenticated %}
  <!-- Sign Up block -->
  <div class="col-md-3 p-2">
        <form action="{% url 'books:check-register' %}" class="bg-light border p-4" method="POST" enctype="multipart/form-data" >
           {% csrf_token %}
       {% for field in rform %}
            <div class="form-group">
              <label>{{field.label}}</label>
              {{ field }}
              <p style="color: red">
                {% if field.errors %}
                {{ field.errors|striptags }}</li>
                {% elif custom_errors %}
                    {% if field.name == "username" %}
                        {{ custom_errors }}    
                    {% endif %}
                {% elif pass_err %}
                    {% if field.name == "password" %}
                        {{ pass_err }}    
                    {% endif %}
                {% endif %}
              </p>
            </div>
              {% endfor %}
          <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
      </div>
      <!-- Sign Up block -->
      {% endif %}
  </div>
  {% endblock %}
  

books/templates/books/search.html
{% extends 'books/base.html' %}

{% block content %}
<!-- body block-->
<h1>Search</h1>
<div class="row" m-3>
  <div class="col">
    <input class="form-control" type="text" name="" id="search" placeholder="search">
  </div>
</div>
<div class="row m-3">
  <div class="col">
    <div id="Authors" style="display: none;">
      <h4>Authors</h4>
    </div>
  </div>
</div>
<div class="row m-3">
  <div class="col">
    <div id="Books" style="display: none;">
      <h4>Books</h4>
    </div>
  </div>
</div>
<div class="row m-3">
  <div class="col">
    <div id="Categories" style="display: none;">
      <h4>Categories</h4>
    </div>
  </div>
</div>

<script type="text/javascript">
    search.addEventListener('change', function(e) {
        var search = document.getElementById('search');
        var myDiv = document.getElementById('myDiv');
        var searchValue = search.value;
        var url = "{% url 'books:search-service' 111 %}".replace('111', searchValue) ;
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                var response = this.responseText;
                response = JSON.parse(response);
                authors = response.results[0];
                books = response.results[1];
                categories = response.results[2];
                
                document.getElementById('Authors').innerHTML = '';
                if (authors.length) {
                    console.log(authors);
                    var ul = document.createElement('ul');
                    for (var i in authors) {
                        var li = document.createElement('li');
                        var a = document.createElement('a');
                        var url = "{% url 'books:author-detail' 111 %}".replace('111', authors[i].id);
                        a.setAttribute('href', url);
                        a.textContent = authors[i].first_name + ' ' + authors[i].last_name;
                        li.appendChild(a);
                        ul.appendChild(li);
                    }
                    document.getElementById('Authors').textContent = 'Authors';
                    document.getElementById('Authors').appendChild(ul);
                    document.getElementById('Authors').style.display = 'block';
                }
                
                document.getElementById('Books').innerHTML = '';
                if (books.length) {
                    console.log(books);
                    var ul = document.createElement('ul');
                    for (var i in books) {
                        var li = document.createElement('li');
                        var a = document.createElement('a');
                        var url = "{% url 'books:book-detail' 111 %}".replace('111', books[i].id);
                        a.setAttribute('href', url);
                        a.textContent = books[i].title;
                        li.appendChild(a);
                        ul.appendChild(li);
                    }
                    document.getElementById('Books').textContent = 'Books';
                    document.getElementById('Books').appendChild(ul);
                    document.getElementById('Books').style.display = 'block';
                }

                document.getElementById('Categories').innerHTML = '';
                if (categories.length) {
                    console.log(categories);
                    var ul = document.createElement('ul');
                    for (var i in categories) {
                        var li = document.createElement('li');
                        var a = document.createElement('a');
                        var url = "{% url 'books:category-detail' 111 %}".replace('111', categories[i].id);
                        a.setAttribute('href', url);
                        a.textContent = categories[i].name;
                        li.appendChild(a);
                        ul.appendChild(li);
                    }
                    document.getElementById('Categories').textContent = 'Categories';
                    document.getElementById('Categories').appendChild(ul);
                    document.getElementById('Categories').style.display = 'block';
                }
                search.value = '';   
            }
        };
        xhttp.open("GET", url, true);
        xhttp.send();
    });
</script>
{% endblock %}